imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.xml"}

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pl

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
      - 'bootstrap_3_horizontal_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

knp_paginator:
    page_range: 10                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
      pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
      sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

lexik_translation:
    fallback_locale: [pl]         # (required) default locale(s) to use
    managed_locales: [pl, en, tr] # (required) locales that the bundle has to manage

easy_admin:
  design:
    menu:
      - { label: 'Tłumaczenia', url: 'https://tag.dashboarddc.com/admin/trans', target: '_blank', icon: 'language' }
      - { entity: 'Agent', label: 'Agenci', icon: 'user' }
      - { entity: 'Category',label: 'Kategorie', icon: 'object-group' }
      - { entity: 'Source', label: 'Źródła', icon: 'external-link' }
      - { entity: 'Tag',label: 'Tagi', icon: 'tag' }
      - { entity: 'Team', label: 'Zespoły', icon: 'users' }
      - { entity: 'TeamSource', label: 'Powiązania zespoł -> źródła', icon: 'link' }
      - { entity: 'TagList', label: 'Lista tagów', icon: 'tags' }
      - { entity: 'ActivityLog', label: 'Logi', icon: 'list' }
  site_name: "Tag admin"
  entities:
    ActivityLog:
      class: AppBundle\Entity\ActivityLog
    Agent:
      class: AppBundle\Entity\Agent
      list:
        fields:
          - id
          - firstname
          - lastname
          - sid
          - sip
          - thulium_login
          - whmcs_admin_id
          - team
      form:
        fields:
          - firstname
          - lastname
          - sid
          - sip
          - thulium_login
          - whmcs_admin_id
          - team
    Category:
      class: AppBundle\Entity\Category
      list:
        fields:
          - id
          - name
          - tags
      form:
        fields:
          - name
          - tags
    Source:
      class: AppBundle\Entity\Source
      list:
        fields:
          - id
          - name
          - slug
          - team_sources
      form:
        fields:
          - name
          - slug
          - team_sources
    Tag:
      class: AppBundle\Entity\Tag
      list:
        fields:
          - id
          - name
          - slug
          - category
      form:
        fields:
          - name
          - slug
          - category
    TagList:
      class: AppBundle\Entity\TagList
    Team:
      class: AppBundle\Entity\Team
      list:
        fields:
          - id
          - name
          - slug
          - agents
          - team_sources
      form:
        fields:
          - name
          - slug
          - agents
          - team_sources
    TeamSource:
      class: AppBundle\Entity\TeamSource
      list:
        fields:
          - id
          - source
          - team
      form:
        fields:
          - source
          - team